// import { HeaderMegaMenu } from "@/components/header/TheHeader";
import type { Metadata } from "next";
import { Provider } from "./provider";
import Header from "@/components/header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<Provider>
				<body>
					<Header />
					<main>{props.children}</main>
				</body>
			</Provider>
		</html>
	);
}
